1. What makes NumPy.shape() different from NumPy.size()?
2. In NumPy, describe the idea of broadcasting.
3. What makes Python better than other libraries for numerical computation?
4. How does NumPy deal with files?
5. Mention the importance of NumPy.empty().

### 1. What makes NumPy.shape() different from NumPy.size()?


In [1]:
# In arrays NUmpy.shape is called as attribute.
# It indicates the shape of an array.  
# Numpy.size is describes the size of an array.

In [1]:
#for example:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [5]:
#finally the difference is shape describes the number of rows and columns in an dimensional array.
#But size attribute describes size of the entire array.

### 2. In NumPy, describe the idea of broadcasting.

In [6]:
# I know something that is :
# Broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.
# the smaller array is "broadcast" across the lager array so they have compatible shapes

In [7]:
# for example:
import numpy as np
a = np.array([1,2,3])
b = 2
c = a + b
print(a)
print(b)
print(c)

[1 2 3]
2
[3 4 5]


In [10]:
# above code is like:
#import numpy as np
#a = np.array([a1,a2,a3])
#b = 2
#c = a + b
#here in 'c' variable is [a1+2,a2+2,a3+2] like that 


### 3. What makes Python better than other libraries for numerical computation?

In [11]:
#using of numpy , scipy , and pandas etc...these are some numerical computations.

### 4. How does NumPy deal with files?

In [12]:
#suppose you can save your numpy to csv files using the savetxt()function.
#the function takes a filename and array as aruguments and saves the array into csv format.thatwise numpy deals with fiels

### 5. Mention the importance of NumPy.empty().

In [13]:
# it returns a new array of given shape and type ,without initializing entries.

In [17]:
import numpy as np
a = np.empty([2,2],dtype = int)
print(a)

[[ 1416207793 -1442142908]
 [ 1902277881  1458157838]]


In [4]:
import numpy as np
a = np.empty([5,4],dtype = int)
print(a)

[[-1078174776         491          38           0]
 [          0           0           0           0]
 [          0     7602273  1634607739   975332717]
 [ 1685353250   578057583  1702109740   975336568]
 [  540039970   540024880  1851546928       32034]]
